### PR TITLE
Ornaments altsym

### PR DESCRIPTION
**Pull request by raffazizzi**
Reopens #233 because target branch for merging has changed from master to develop.

### CODE REVIEW

**Comment by ahankinson** [comment]
Could you please move the test file for `altsym` to the `tests` directory that is now in `develop`? If you want to test it against CMN and All, you can make two copies of the file.

Thanks!

**Comment by ahankinson** [comment]
Can you rebase this against `develop-perry` (which is where a lot of the development is currently happening)? I'll then press the big green button and merge it in.

**Comment by raffazizzi** [comment]
I've rebased - hadn't done this before so sorry if the history ended up a bit messy. Happy to start over if needed.

**Comment by ahankinson** [comment]
OK, so it looks like it's only eb70fe3 that changes mei-source.xml. Is this correct?

@pe-ro I can merge this into 'develop' and also into 'develop-perry,' since that will probably make it easiest for you to integrate this change.

In the future we'll have a smoother process for this, but I think this will work. :)

**Comment by raffazizzi** [comment]
Yes, though the conflict was with the regenerated schema (fb396cd), not the ODD

**Comment by ahankinson** [comment]
OK.

@pe-ro if you let me know when you're done with mei-source.xml for the day, I'll merge Raff's stuff so that you can update your copy tomorrow morning.

**Comment by pe-ro** [comment]
I’ve made several commits to /develop that did not have any issue number associated with them, but now I’m ready to commit the first set of changes that deals with an issue.  What’s the magic phrase to put in the commit message to close the issue?

**Comment by ahankinson** [comment]
"Fixes #1234"

**Comment by ahankinson** [comment]
Better yet: https://github.com/music-encoding/music-encoding/blob/develop/CONTRIBUTING.md#message-summary-1

**Comment by pe-ro** [comment]
Thanks.  Now I'm done for the day.

**Comment by pe-ro** [comment]
Except the issue didn't actually get closed.  What now?

**Comment by ahankinson** [comment]
It will close itself when we merge the commit with master.

**Comment by pe-ro** [comment]
OK, thanks.  I'm out.

**Comment by ahankinson** [comment]
Ok, merged but Travis isn't happy. I think it's just because the migration isn't quite done yet on mei-source.xml, and the `@meiversion` attribute is still set to the wrong value.

https://travis-ci.org/music-encoding/music-encoding/builds/83986988

There's also another failure there, something about 'height' not being allowed. I'll let you fix that one.

**Comment by pe-ro** [comment]
Hmmm. I don't know what's going on with the height attribute.  I'm inclined to let it slide until I get all the changes done, then take it up (along with other remaining problems, of which I'm certain there will be some).

**Pull request merged**
