### PR TITLE
Improve neumes nesting

### LINKED ISSUE #968: Request for making several elements valid in mei-neume dev-5.0.0 schema
As shown in the figure below, the underlined elements are not valid in the mei-neume dev-5.0.0 schema. The details and examples are as follows. All the examples are from Einsiedeln (CH-E_611).

mei-Neumes   dev copy

1. `<accid>` is not valid both inside and outside a syllable, but it happens both inside and outside.

inside:
018 flat inside 1 - folio
018r flat inside 1 - mei

018r flat inside 2 - folio
018r flat inside 2 - mei

outside:
260r flat outside - folio
260r flat outside - mei

261v flat outside - folio
261v flat outside - mei

2. `<divLine>` is only valid inside a syllable, but it is mostly outside.

044r divisio outside - folio
044r divisio outside - mei

267v divisios outside - folio
267v divisios outside - mei

3. `<clef>`is only valid outside a syllable, but sometimes it is inside.

270v clef inside 1 and 2 - folio
270v clef inside 1 and 2 - mei

061v clef inside - folio
061v clef inside - mei

Compared to mei-all dev-5.0.0 schema, all the elements mentioned above but `<accid>` (also needs to be fixed) are valid both inside and outside a syllable. 

mei-all   dev copy

### PR DESCRIPTION
**Pull request by kepper**
fixes #968

### CODE REVIEW

**Comment by martha-thomae** [comment]
This seems to finish solving issue #968. Now both in mei-Neumes and mei-all, we have the following: 

### mei-Neumes
Screen Shot 2022-10-12 at 7 31 38 PM

### mei-all
Screen Shot 2022-10-12 at 7 32 15 PM

Only `<custos>` inside `<syllable>` is marked as invalid and everything else is accepted inside and outside `<syllable>` (`<accid>`, `<clef>`, and `<divLine>`—this last one fixed in the current PR). So, all changes asked in https://github.com/music-encoding/music-encoding/issues/968#issuecomment-1146583421 have been completed.

**Review by martha-thomae — APPROVED** [review]

**Comment by fujinaga** [comment]
Looks good.

**Review by fujinaga — APPROVED** [review]
Looks good.

**Review by fujinaga — APPROVED** [review]

**Comment by martha-thomae** [comment]
I don't know why the "merge pull request" button is blocked as it has the two approving reviews. But I guess I would always prefer one of the technical co-chairs to merge it @bwbohl and @musicEnfanthen. Thanks for the PR @bwbohl!

**Comment by bwbohl** [comment]
thx @fujinaga and @martha-thomae for reviewing and @kepper for fixing ;-)

**Pull request merged**
