### PR TITLE
Fix copy of web-folder when creating guidelines-html

### PR DESCRIPTION
**Pull request by bwbohl**
This PR most importantly redefines the copy procedure for assets needed when building the guidelines. Before only the css folder in `/source/web` was copied, now all contents of `source/web` are being copied.
Moreover the PR introduces a fail-on-error for the transformation of the canonicalised source to the guidelines html; before this PR the build would complete with "SUCCESS" even though the transformation had failed.

### CODE REVIEW

**Review by ahankinson — DISMISSED** [review]

**Comment by ahankinson** [comment]
@music-encoding/core-contributors could someone else please review this and merge? thx.

**Comment by bwbohl** [comment]
@kepper could you please have a try and especially clarify whether it is correct to delete fuse.js

**Comment by bwbohl** [comment]
@kepper just a second try ;-)

> @kepper could you please have a try and especially clarify whether it is correct to delete fuse.js

**Comment by bwbohl** [comment]
just another reminder @kepper

**Comment by kepper** [comment]
sorry, I didn't find this ticket when looking for it recently ;-) Thanks for pinging again, @bwbohl  – I'll look into this today…

**Comment by musicEnfanthen** [comment]
ODD meeting 2022_01_28: After merging #895 (update of Saxon to v10), this PR has merge conflicts. @bwbohl could you include those latest changes, please, to resolve the conflicts.

After the conflicts are fixed, would be great to ping @kepper for a second approving review.

**Comment by bwbohl** [comment]
although I just fixed the conflict, if I understand #847 correctly, `fuse.js` is not to be removed, right?

**Comment by kepper** [comment]
eventually we need it, yes. Probably my fault back then when you did this – I never really worked out what is copied over from where to where in these actions :-/

**Comment by lpugin** [comment]
I have no experience with `fuse.js`. However, we use `lunr.js` in different websites, including with indexes pre-built during GitHub actions (e.g., in https://rism.info/search.html). I am happy to help if you think `lunr.js` could work for the guidelines.

**Comment by bwbohl** [comment]
finally got this sorted… removing fuse.js as I did in 303cc3c266c02d960db6d415f41b638d5480d16b is perfectly fine, as it was a duplicate of https://github.com/music-encoding/music-encoding/blob/develop/source/web/search/fuse.min.js; so actually this is read to merge and should bring up search functionality in the dev eversion of the guidelines!

**Review by rettinghaus — APPROVED** [review]

**Comment by bwbohl** [comment]
@rettinghaus sorry for re-requesting, @kepper please review

**Review by kepper — APPROVED** [review]
paths seem to be correct (unable to actually test on computer at hand…)

**Comment by bwbohl** [comment]
@rettinghaus or @ahankinson could you please test it locally and add your review?

**Comment by rettinghaus** [comment]
Tested it and for me everything works fine.

**Review by ahankinson — APPROVED** [review]

**Comment by ahankinson** [comment]
Merged, thanks!

**Comment by bwbohl** [comment]
@thx for merging

**Pull request merged**
