### PR TITLE
Fix(MEI.edittrans): Replace special entities with proper links

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
Thank you @rettinghaus. There seems to be at least another place with special entities in https://github.com/music-encoding/music-encoding/blob/develop/source/modules/MEI.shared.xml#L3769

**Comment by rettinghaus** [comment]
Yes, because this addressed in #1046.

**Comment by rettinghaus** [comment]
Since #1046 is merged, this should be good to go now, @musicEnfanthen.

**Review by musicEnfanthen — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
@bwbohl @ahankinson Could one of you do a second review?

**Review by bwbohl — APPROVED** [review]

**Review by ahankinson — APPROVED** [review]
Nice catch @rettinghaus

**Pull request merged**
