### PR TITLE
guidelines: integrating @pe-ro 's adjustments for sourceDesc

### PR DESCRIPTION
**Pull request by riedde**
Refs #1353

### CODE REVIEW

**Comment by rettinghaus** [comment]
@riedde maybe you should rebase on Perry's branch?

**Comment by riedde** [comment]
@rettinghaus I did it. Sorry for the strange branching ...

**Comment by musicEnfanthen** [comment]
So I guess it is all about these two commits?

https://github.com/music-encoding/music-encoding/pull/1419/commits/cccf6986c23aa9df6624ce23654a473d24e32a2a
https://github.com/music-encoding/music-encoding/pull/1419/commits/ac7bd563a559f7ff66fa5e17b7740fe6aca6df39

**Comment by musicEnfanthen** [comment]
And it is going to @pe-ro's branch to 1) bring it in synch with develop, and 2) add the guidelines examples for it, right?

**Comment by riedde** [comment]
Yes, sadly i committed on a seperate branch. Noticed afterwarts.

**Comment by musicEnfanthen** [comment]
OK. I think after the merge it will be a bit cleaner.

**Pull request merged**
