### PR TITLE
guidelines: insert fallen out div at the end of chapter 3.3

### PR DESCRIPTION
**Pull request by riedde**
Following the proposal from the ODD-Meeting 11/2024, see https://github.com/music-encoding/music-encoding/pull/1353/files#r1863530669

### CODE REVIEW

**Comment by riedde** [comment]
@bwbohl @musicEnfanthen I hadn't the possibility to test it, but should work. Willing to work on it, if necessary!

**Review by musicEnfanthen — DISMISSED** [review]
Looks good, thank you!

**Comment by musicEnfanthen** [comment]
@riedde can you change the target branch to develop, please? (This way, we can decouple this move from the addition of `p` in `source` which is about to be delayed a bit more)

**Comment by riedde** [comment]
Oh, damn. I used the webinterface and didn't care about the target branch. @musicEnfanthen done!

**Comment by musicEnfanthen** [comment]
@riedde Ah, sorry, this will not work. It now includes all the changes from the former target branch as well :(

**Comment by riedde** [comment]
@musicEnfanthen So I'll close this and open a new PR

**Comment by musicEnfanthen** [comment]
Superseded by #1567

**Pull request closed without merging**
