### PR TITLE
build: update stylesheets for build

### PR DESCRIPTION
**Pull request by rettinghaus**
There was a very nasty bug in the Stylesheets (see TEIC/TEI/issues/2597). As far as I know this didn't affect our customizations, but we should update anyway.

### CODE REVIEW

**Review by musicEnfanthen — DISMISSED** [review]
Looks good to me, thank you!

**Comment by musicEnfanthen** [comment]
Sorry, @rettinghaus . May I ask you to also update the stylesheets version in https://github.com/music-encoding/music-encoding/blob/develop/BUILD_COMMANDLINE.md ?

**Review by bwbohl — DISMISSED** [review]

**Comment by rettinghaus** [comment]
@musicEnfanthen missed that one again, sorry.

**Review by musicEnfanthen — APPROVED** [review]

**Review by bwbohl — APPROVED** [review]
@rettinghaus thanks for taking care ;-)

**Pull request merged**
