### PR TITLE
Allow divLine inside and outside syllable

### PR DESCRIPTION
**Pull request by rettinghaus**
Another piece to the puzzle #968

### CODE REVIEW

**Comment by kepper** [comment]
trying to work out the difference between this and #1019, I tried to validate according to the requirements specified in https://github.com/music-encoding/music-encoding/issues/968#issuecomment-1146583421. Compared to that, this solution doesn't support `<accid>` neither inside nor outside of `<syllable>` (which means inside `<layer>`). I prefer the simplicity of this solution, but it doesn't go the whole way, and so I think we should go with #1019 instead of this one for now, insisting on the proposal in the comment over there: 

> we encourage the IG to schedule a meeting to jointly clean up this part of MEI

**Comment by bwbohl** [comment]
@martha-thomae and @fujinaga in the light of #1019 having been merged, is there anything left here or can this be closed?

**Comment by fujinaga** [comment]
> @martha-thomae and @fujinaga in the light of #1019 having been merged, is there anything left here or can this be closed?

I think it can be closed.

**Comment by musicEnfanthen** [comment]
@rettinghaus Also ok with closing this?

**Comment by musicEnfanthen** [comment]
Thank you @rettinghaus

**Pull request closed without merging**
