### PR TITLE
schema: make directive-like elements member of att.verticalGrp

### PR DESCRIPTION
**Pull request by pe-ro**
Make bend, caesura, cpMark, metaMark, ornam, harm, fing, fingGrp, fermata, harpPedal, octave, mordent, trill, and turn members of att.vertical.Grp.

### CODE REVIEW

**Comment by pe-ro** [comment]
Closes #1379

**Comment by musicEnfanthen** [comment]
@pe-ro You also mentioned `<breath>` in #1379, but it is not updated here? By accident?

**Comment by pe-ro** [comment]
@musicEnfanthen, yep, `<breath>` was omitted by mistake. I'll make another PR that includes just `<breath>`.

**Comment by musicEnfanthen** [comment]
@pe-ro Thanks for clarification. 

We could include it in this PR, so everything would be in a single place? You would just need to commit once more to the `develop-vgrp` branch. If that's not possible just let me know, and I can add it.

**Review by musicEnfanthen — APPROVED** [review]

**Review by rettinghaus — APPROVED** [review]

**Pull request merged**
