### PR TITLE
Fix broken build due to failing datatype recognition

### LINKED ISSUE #999: build fails after merge of PR
After mergin #678, the build workflow is broken. This seems to be due to the genericSpecFuntion.xsl checking for rng:choice in dataSpecs (lines 728-745) not recognizing the defined datatypes in https://github.com/music-encoding/music-encoding/pull/678/files#diff-6f6fa3f8400740c85b98fa07c71d68655fbc4ccbdc10a86380cb81f6c6d3dcdfR1906-R1925

### PR DESCRIPTION
**Pull request by kepper**
should enable proper building again

### CODE REVIEW

**Comment by kepper** [comment]
the build failed as a new attributes from #678 introduced a use of rng:ref not seen by the stylesheets so far. This one fixes it locally.

**Comment by musicEnfanthen** [comment]
Fixes #999

**Review by rettinghaus — APPROVED** [review]
Looks good.

**Review by musicEnfanthen — APPROVED** [review]

**Review by lpugin — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
Thanks for the fix.

**Pull request merged**
