### PR TITLE
Updating guidelines for accid.ges

### PR DESCRIPTION
**Pull request by lpugin**
Clarifying the use of accid.ges following discussion #261

### CODE REVIEW

**Comment by ahankinson** [comment]
Is this still the desired wording?

**Comment by zolaemil** [comment]
As far as I understand, there's a consensus that this wording would be better. 

However we haven't reached a conclusion on how to address the consequences: 
1. forget prima practica
2. allow both practices, but require an explicit statement which practice is in use in a particular customization.

As Jo reminds us, MEI is a framework, and one of it's greatest power is documentation, so I too lean towards the second option.

**Comment by lpugin** [comment]
Unless we can clearly identify the advantage of having two practices I would suggest to forget the prima practica, at least for now. We can still adopt it later but with the addition of an encoded description of it in <encodingDesc> as suggested in the discussion. This pull request is fixing the inconsistency we currently have between the documentation and all our examples.

**Comment by ahankinson** [comment]
I will wait for Perry's changes to be merged into develop before merging this one.

**Comment by lpugin** [comment]
I guess this can now be ignored since @pe-ro has clarified the use of accid.ges

**Comment by zolaemil** [comment]
@lpugin do we have a link to the other thread?

**Comment by lpugin** [comment]
https://github.com/music-encoding/music-encoding/pull/261

**Comment by pe-ro** [comment]
Yeah, I think adding `@visible` on `<accid>` and `<artic>` isn't necessary at this point.

**Pull request closed without merging**
