### PR TITLE
Create pr-labeler.yml

### PR DESCRIPTION
**Pull request by bwbohl**
This is a test implantation of the GHActions Labeler to automatically label pulls requests based on the files they modify. At the moment there is an issue with our labels having »:« in their names as I don't know how to mask them in the .yml.

Currently only set for labels Comoponent Workflows and Component Core Schema

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
Nice action. :) 

Ad masking: Did you try to use quotes around the key? (cf. https://stackoverflow.com/questions/14873227/escaping-colons-in-yaml)

**Comment by bwbohl** [comment]
> Nice action. :)
> 
> Ad masking: Did you try to use quotes around the key? (cf. https://stackoverflow.com/questions/14873227/escaping-colons-in-yaml)

No actually not… gotta give it a try

**Comment by bwbohl** [comment]
masking works perfectly thanks @musicEnfanthen!

**Comment by musicEnfanthen** [comment]
Perfect

**Comment by musicEnfanthen** [comment]
Do you want that one to be merged already, or do you want to add more labels first?

**Review by rettinghaus — APPROVED** [review]

**Comment by bwbohl** [comment]
probably we cann merge it already and add other locations later?

**Review by musicEnfanthen — APPROVED** [review]
Looks good. Thanks!

**Comment by musicEnfanthen** [comment]
Unfortunately, you will need another reviewer with write access to get this merged. Maybe @kepper or @lpugin can help?

**Comment by lpugin** [comment]
I am curious to know if this works with PRs coming from external contributors. Do you know if this will work?

**Review by lpugin — APPROVED** [review]

**Pull request merged**
