### PR TITLE
pureODD: Rename macroSpec to dataSpec

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR changes the outdated `macroSpec` into `dataSpec` for data type specifications.

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
@rettinghaus Thank you for this PR. Can we find a more specific PR title, please, like "Rename macroSpec to dataSpec"? And could you provide some short background information why/when macroSpec was outdated?

**Comment by ahankinson** [comment]
It looks like it was deprecated with the move to "Pure ODD". 

Documentation here: https://tei-c.org/Vault/P5/3.4.0/doc/tei-p5-doc/en/html/ref-macroSpec.html

Discussion here: https://github.com/TEIC/TEI/issues/1737

Other discussion on the TEI mailing list here: https://lists.tei-c.org/pipermail/tei-council/2018/024993.html

**Comment by musicEnfanthen** [comment]
Thanks. Do I read it correctly from the sources above, that the `type` attribute was completely deprecated and removed? So what do we do with `macroSpec[@type = 'pe']`

Also, there are some more XSLTs that need to be considered for `macroSpec[@type = 'dt']`:
- https://github.com/music-encoding/music-encoding/blob/1e2ee013d822d7c7b99ae22b83fc5c854d789055/utils/guidelines_xslt/odd2html/specs/moduleSpecs.xsl#L119
- https://github.com/music-encoding/music-encoding/blob/c3f27ed65f07cc27cebb01910959912ecec7be0f/utils/guidelines_xslt/odd2html/globalVariables.xsl#L157
- https://github.com/music-encoding/music-encoding/blob/c3f27ed65f07cc27cebb01910959912ecec7be0f/utils/guidelines_xslt/odd2html/specs/dataTypeSpecs.xsl#L18

**Comment by ahankinson** [comment]
Yes, I think the `@type` parameter should probably be removed from all the `macroSpec` elements.

**Comment by ahankinson** [comment]
@rettinghaus @musicEnfanthen Can we prioritize merging this? I'm noticing that not having this change in means that there are some newer PRs that still have the old `macroSpec` so we're going to get out-of-sync.

**Comment by musicEnfanthen** [comment]
Pinging @lpugin @kepper and @pe-ro who are still in the meeting room

**Comment by musicEnfanthen** [comment]
But maybe it is easier to go with other PRs first (with the old macroSpec), and in the end @rettinghaus would need to adjust this draft here anyway?

**Comment by ahankinson** [comment]
What else is left to be done? I think @rettinghaus fixed the things you brought up, and also removed the `@type` from `macroSpec`

**Comment by kepper** [comment]
I am very strong on pushing this down the road. Changing this markup will break guidelines generation, and I don't want to rush this. This doesn't mean it's a bad idea in general, but it's a bad idea for now. Nothing should wait for it. Sorry…

**Comment by rettinghaus** [comment]
Schemas build fine, Guidelines seems to work. Needs some more checks.

**Comment by bwbohl** [comment]
I'm all in for pureODD, but please let us tackle this after we come up with a stable MEI 5 release.

**Comment by musicEnfanthen** [comment]
Maybe we could meanwhile prepare a list that contains all the necessary steps to move to pure odd (in MEI 6)? That could help to provide a bigger picture of the expected changes and workload.

**Comment by rettinghaus** [comment]
closing due to too many conflicts

**Pull request closed without merging**
