### PR TITLE
Update tei.css

### PR DESCRIPTION
**Pull request by rettinghaus**
This updates the used `tei.css` to the version from the latest release. 
As far as I can see this is basically a clean-up and reorder thing, so this shouldn't hurt. But in any case @kepper should give it a test run.

### CODE REVIEW

**Comment by bwbohl** [comment]
@kepper any chance of reviewing this before next ODD meeting?

**Comment by kepper** [comment]
I'll see what I can do…

**Review by kepper — APPROVED** [review]
running it locally seems fine – at least I couldn't find any substantial differences within a reasonable testing time. We do have some font issues, but they are unrelated to this, so I will try to address them separately… Many thanks for updating this, @rettinghaus 👍

**Review by ahankinson — APPROVED** [review]

**Comment by ahankinson** [comment]
Looks good to me. Will wait for one of the co-chairs to merge at the ODD meeting unless I hear otherwise.

**Pull request merged**
