### PR TITLE
docs: fix description of values in data.COURSETUNING

### LINKED ISSUE #1550: Missing value in COURSETUNING
In `data.COURSETUNING` there is the value `lute.baroque.d.minor` available, but no equivalent `lute.baroque.d.major`.
Are the available values complete and are their spellings correct?

### PR DESCRIPTION
**Pull request by rettinghaus**
closes #1550

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
@TimCrawford @DILewis @paul-bayleaf Could you have a short look at this PR to confirm it suits your needs?

**Comment by musicEnfanthen** [comment]
@music-encoding/ig-tablature Could anyone review (or at least confirm) the proposed changes please? Would be great to have this fixed in 5.1

**Review by DILewis — APPROVED** [review]

**Review by DILewis — APPROVED** [review]

**Review by musicEnfanthen — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
Thank you @DILewis !

**Comment by bwbohl** [comment]
thx

**Review by bwbohl — APPROVED** [review]

**Pull request merged**
