### PR TITLE
stylesheets: fix submodules

### PR DESCRIPTION
**Pull request by rettinghaus**
I had build problems with latest develop. It seems that some merged changed the submodule at some point. 

I made another 

`git submodule update --recursive --remote`

Now everything is working fine again for me.

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
Probably this one? https://github.com/music-encoding/music-encoding/commit/c161cf0fce91e844d34e18e6aff32360fe411a1d

**Comment by rettinghaus** [comment]
Looks like it, yes.

**Comment by musicEnfanthen** [comment]
So just for documentation, the former merge moved the stylesheets from 7.56 back to 7.55 by mistake. This PR moves them back again from 7.55 to 7.56, correct?

**Comment by rettinghaus** [comment]
Correct.

**Comment by musicEnfanthen** [comment]
Thanks!

**Review by musicEnfanthen — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
Pinging @bwbohl

**Review by bwbohl — APPROVED** [review]

**Pull request merged**
