### PR TITLE
fix data.COLOR

### PR DESCRIPTION
**Pull request by rettinghaus**
This is a small fix to correct the description after the update from #599.

### CODE REVIEW

**Comment by ahankinson** [comment]
I think these are all taken from the available CSS notation formats (https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) so do we need to list them all individually? Can we point to the CSS specification for all available formats? (If that's the case then we need to also make sure our tools support `rgba()` and `hsl()` functions... but that's a slightly different story.

There's also differing guidance on whether it's RRGGBBAA or AARRGGBB. 

https://www.digitalocean.com/community/tutorials/css-hex-code-colors-alpha-values

https://caniuse.com/css-rrggbbaa

From what I can tell it's supposed to be RRGGBBAA for CSS and browsers.

**Comment by rettinghaus** [comment]
Changed `AARRGGBB` to `RRGGBBAA`. However, it would be indeed good to know if this is _only a fix_ or a breaking change.

**Comment by craigsapp** [comment]
> From what I can tell it's supposed to be RRGGBBAA for CSS and browsers.

Yes it is only RGBA and never ARGB (so it is a fix rather than a backwards compatibility problem).

**Comment by ahankinson** [comment]
I did find reference to some platforms using Alpha channel first (Android) but I think this is probably the exception and not the rule.

**Comment by craigsapp** [comment]
They must have colorful webpages 😉

**Comment by rettinghaus** [comment]
Just to add: MEI supports a subset from the [CSS Color Module Level 4](https://www.w3.org/TR/css-color-4):

> The color-functions are [<rgb()>](https://www.w3.org/TR/css-color-4/#funcdef-rgb), [<rgba()>](https://www.w3.org/TR/css-color-4/#funcdef-rgba), [<hsl()>](https://www.w3.org/TR/css-color-4/#funcdef-hsl), [<hsla()>](https://www.w3.org/TR/css-color-4/#funcdef-hsla), [<hwb()>](https://www.w3.org/TR/css-color-4/#funcdef-hwb), [<lab()>](https://www.w3.org/TR/css-color-4/#funcdef-lab), [<lch()>](https://www.w3.org/TR/css-color-4/#funcdef-lch), [<oklab()>](https://www.w3.org/TR/css-color-4/#funcdef-oklab), [<oklch()>](https://www.w3.org/TR/css-color-4/#funcdef-oklch), and [<color()>](https://www.w3.org/TR/css-color-4/#funcdef-color).

We adopted all color names from CSS 4 draft, but `data.COLORVALUES` wasn't touched.

**Review by ahankinson — APPROVED** [review]

**Review by bwbohl — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
Thank you everyone!

**Pull request merged**
