### PR TITLE
Make att.pedal.vis member of att.verticalGroup. Fixes #610

### LINKED ISSUE #610: Allow @vgrp as attribue of <pedal>
`@vgrp` should be a valid attribute of `<pedal>` (just as of `<dynam>` and `<hairpin>`), so that vertical alignment is also formally possible. Verovio renders already it correctly, see discussion at rism-ch/verovio#774.

### PR DESCRIPTION
**Pull request by lpugin**
* See related GitHub discussions for more background

### CODE REVIEW

**Review by rettinghaus — APPROVED** [review]

**Comment by wergo** [comment]
This would be great!

**Comment by lpugin** [comment]
@kepper and @bwbohl anything problematic with the PR?

**Comment by lpugin** [comment]
Some feedback would be appreciated.

**Review by kepper — APPROVED** [review]
sounds reasonable to me – apologies for the delay, and thanks for the work on this…

**Comment by kepper** [comment]
should be merged on the next ODD Friday…

**Pull request merged**
