### PR TITLE
Make number attributes available for mRpt

### PR DESCRIPTION
**Pull request by rettinghaus**
addresses #942
connected to #853

### CODE REVIEW

**Review by ahankinson — APPROVED** [review]

**Review by bwbohl — APPROVED** [review]

**Comment by bwbohl** [comment]
although this is already ready-to-merge, any chance of fixing #853 until next ODD meeting?

**Comment by ahankinson** [comment]
With two approving reviews the PR can be merged

**Comment by ahankinson** [comment]
Oops! Sorry @bwbohl i missed your comment! Shall I revert?

**Comment by bwbohl** [comment]
i think it's fine

**Pull request merged**
