### PR TITLE
make clef part of visualOffset

### PR DESCRIPTION
**Pull request by rettinghaus**
There hasn't been a way to shift clefs.

### CODE REVIEW

**Comment by rettinghaus** [comment]
Used for something like this:
587a5766-cd00-11e6-9752-47a51bbc4141

```xml
<layer>
  <clef shape="F" line="4" fontsize="tiny" vo="-15" />
</layer>
```

**Comment by bwbohl** [comment]
the build error is due to the deprecated maven-repo URL

**Review by kepper — APPROVED** [review]
sounds good :-)

**Comment by kepper** [comment]
ready to be merged at tomorrow's ODD Friday

**Pull request merged**
