### PR TITLE
fixed duplicate ids

### PR DESCRIPTION
**Pull request by rettinghaus**
* fix for #534 
* added some authority control

### CODE REVIEW

**Comment by ahankinson** [comment]
Raffaele Viglianti is http://viaf.org/viaf/8151836518820400567
Benjamin Bohl is http://viaf.org/viaf/173389559

**Comment by rettinghaus** [comment]
Not really: 
Raff has a duplicate entry: http://viaf.org/viaf/8151594445705352922
Benjamin is undifferentiated (i.e. it's just a placeholder entry)

**Comment by ahankinson** [comment]
https://orcid.org/0000-0003-3094-139X  -- Raff
https://orcid.org/0000-0001-7217-9167 -- Benny

**Comment by rettinghaus** [comment]
Fine, if it's ok to mix them.

**Comment by ahankinson** [comment]
Merged! Thanks.

**Pull request merged**
