### PR TITLE
docs: update copyright dates

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR updates all copyright notices to the current year to match the recent changes in the tablature chapter.

### CODE REVIEW

**Comment by lpugin** [comment]
Do we really need this date range? Maybe we can drop it so we don't have to update it every year....

**Comment by rettinghaus** [comment]
It's common practice. And we didn't update it every year, only for the last release.

**Comment by lpugin** [comment]
I think this is a useless practice. Having the creation date is fine, but having a date range quite inevitably becomes not updated at some point. That makes things look not maintained, or worse, not under copyright any more. Plus it creates some useless noise in the history of the files, so I would suggest to drop the end date.

**Comment by ahankinson** [comment]
cURL has removed the years from the source code:

https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/

Facebook also dropped the years from the React source code:

https://github.com/facebook/react/commit/b87aabdfe1b7461e7331abb3601d9e6bb27544bc

Here's a blog post about the topic: 

https://hynek.me/til/copyright-years/

I'd be ok with removing the dates altogether.

**Comment by musicEnfanthen** [comment]
I don't think it is useless, there is some value in having an end date. But you are right, the most important date is the first one which claims the start of the copyright (in case of legal disputes).

BTW, you do not loose copyright due to a wrong date. ;) In fact, author's rights are automatically applied under the Berne Convention so things are under copyright even if you wouldn't have a copyright statement (with some exceptions for the US, of course). The statement just makes these claims a bit more visible and easier to find.

This also seems to be some of the reasoning behind the decisions made by cURL et al. to skip the years altogether.

**Comment by ahankinson** [comment]
We could update the LICENSE file to keep the years there? Then there would only be one place. Currently it doesn't have them.

**Comment by musicEnfanthen** [comment]
Yes, I think that's in any case a good idea to add the dates there.

If we want to keep any dates elsewhere, maybe the solution facebook used before they removed the dates could be elegant (and does not require updates)? 

`Copyright (c) 2017-present ...`

**Comment by musicEnfanthen** [comment]
Superseded by #1533

**Pull request closed without merging**
