### PR TITLE
make mRest and multiRest part of att.color

### LINKED ISSUE #718: @color for mRests and multiRests
Currently mRests and multiRests do not have a color attribute.   

https://music-encoding.org/guidelines/v4/elements/multirest.html
https://music-encoding.org/guidelines/v4/elements/mrest.html

This should be added for symmetry with rests, which do have a color attribute.

https://music-encoding.org/guidelines/v4/elements/rest.html

Related to issue https://github.com/rism-ch/verovio/issues/1748.

### PR DESCRIPTION
**Pull request by rettinghaus**
fixes #718

### CODE REVIEW

**Review by kepper — COMMENTED** [review]
thanks for taking this up so quickly :-) Everything fine, but shouldn't we include `<multiRpt>` as well, so add it also to `att.multiRpt.vis`?

**Comment by craigsapp** [comment]
Here is a test for multimeasure repeats (and measure repeats and half-measure repeats) which are currently not colorable in verovio:


Screen Shot 2020-10-16 at 12 48 59 AM


```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-10-16T00:46:01" version="3.1.0-dev-887e034-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000197310981">
    <score xml:id="score-0000001220595066">
     <scoreDef xml:id="scoredef-0000000530066489">
      <staffGrp xml:id="staffgrp-0000000349387557">
       <staffDef xml:id="staffdef-0000000870342583" n="1" lines="5">
        <clef xml:id="clef-0000001581917438" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000001787997131" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L4F1-L5F1">
          <note xml:id="note-L4F1" dur="8" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L5F1" dur="8" oct="4" pname="d" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L6F1-L7F1">
          <note xml:id="note-L6F1" dur="8" oct="4" pname="g" accid.ges="n" />
          <note xml:id="note-L7F1" dur="8" oct="4" pname="f" accid.ges="n" />
         </beam>
         <beatRpt xml:id="beatrpt-L8F1" color="red" />
         <beatRpt xml:id="beatrpt-L12F1" color="orange" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L16">
       <staff xml:id="staff-L16F1N1" n="1">
        <layer xml:id="layer-L16F1N1" n="1">
         <mRpt xml:id="mrpt-L17F1" color="limegreen" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L17">
       <staff xml:id="staff-L16F1N2" n="1">
        <layer xml:id="layer-L16F1N2" n="1">
         <multiRpt xml:id="multirpt-L17F2" color="skyblue" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L23">
       <staff xml:id="staff-L23F1N1" n="1">
        <layer xml:id="layer-L23F1N1" n="1">
         <beam xml:id="beam-L24F1-L25F1">
          <note xml:id="note-L24F1" dur="8" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L25F1" dur="8" oct="4" pname="d" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L26F1-L27F1">
          <note xml:id="note-L26F1" dur="8" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L27F1" dur="8" oct="4" pname="d" accid.ges="n" />
         </beam>
         <halfmRpt xml:id="halfmrpt-L28F1" color="violet" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Comment by rettinghaus** [comment]
@kepper good catch! Until now only repeat element without color.

**Review by kepper — APPROVED** [review]
should be ready now, right? Thanks again, I guess we'll merge later today during the ODD Friday…

**Comment by kepper** [comment]
actually, there is some overlap with #626, so we need to be careful when merging

**Comment by rettinghaus** [comment]
@kepper if you approve #626 I'll remove the change over here (or over there, as it was a single commit).

**Pull request merged**
