### PR TITLE
Tablature IG current status

### LINKED ISSUE #1427: Tablature customization

### PR DESCRIPTION
**Pull request by lpugin**
This is a draft PR for providing a better understanding of the current status of the tablature IG customization.

### CODE REVIEW

**Comment by lpugin** [comment]
@music-encoding/ig-tablature since these are now quite old ideas, @kepper and @pe-ro will have a look to make sure there is nothing wrong with them.

**Comment by pe-ro** [comment]
I had a look at one of the example files, da_crema-1546_10-no_6, to see how it fared when parsed against v. 5 and my proposed header changes for v. 6.  Since this is a v. 3 file, I expected a lot of changes to be required; however, the necessary changes appear to be minimal.  Setting the header changes aside, the only new elements and attributes found were: `<tabGrp>`, `note/@tab.course`, and `fing/@playingHand` and `fing/@playingFinger` (which need to be renamed to "playinghand" and "playingfinger" to match current attribute naming rules).

`<tabGrp>` and its child, `<tabDurSym>`, are necessary additions for the tablature repertoire.  Elevating the durational symbol to an element makes it possible to wrap the symbol in editorial markup, such as `<sic>` and `<corr>`, when the visual symbol diverges from the logical one encoded in `@dur`.

`@tab.course` can be a substitute for `@tab.string` in the tablature customization or the name change can be applied universally.  

I recommend removing `@playingfinger`, as the content of `<fing>` can be used to indicate the finger used while also offering more visual rendition possibilities than an attribute can support.  The addition of `@playinghand` is needed for instruments that are played with 2 hands.  However, since an attribute can't offer any visual rendition possibilities, I recommend encoding the playing hand with  an additional `<fing>` element and differentiating the hand and finger elements with `@type` or a similar attribute.

All this being said, the example file doesn't validate against the provided RNG schema, mei-frettab.rng.  My guess is that the example file describes an intended result/state that the schema doesn't yet support.  At some point, of course, this must be remedied.  I'm also unclear why DTD and XSD schemas are provided, since MEI gave up supporting these schema formats.

Perhaps I chose the sample file unwisely.  It would be beneficial to repeat the experiment with another file, perhaps one for guitar instead of lute.

@kepper ?

**Comment by lpugin** [comment]
I left `tab.string` with the idea that this could go into an MEI 5.1. However, since we are now looking at having this for version 6.0, then it can be removed. I am going to update the PR accordingly once @kepper has also commented on it.

**Comment by DILewis** [comment]
Just to pick up on the query by @pe-ro about schema files, if this is a reference to the ones in the tablature-ig repo, they're very old, and preserved only for reference (probably we should delete them). They're the ones that Richard Lewis devised when we first proposed some of these things at the Music Encoding Conference in 2015(!) Most of the elements have changed since then, as has the MEI schema.

**Comment by pe-ro** [comment]
Thanks, @DILewis.  Where are the latest ODD and/or schema files?

**Comment by DILewis** [comment]
> Thanks, @DILewis. Where are the latest ODD and/or schema files?

I don't know how far @kepper got with working on this. Otherwise, the only thing I've seen are @lpugin 's mods to get Verovio working (e.g. [here](https://github.com/rism-digital/verovio/blob/develop/libmei/mei/mei-verovio_compiled.odd)), but I think these focus on attributes rather than elements and prioritise getting rendering working over implementing the full model.

**Comment by musicEnfanthen** [comment]
@lpugin @DILewis What's the status of this PR? Any updates from the dev workshop that still need to be included?

**Comment by musicEnfanthen** [comment]
Pinging @lpugin @DILewis Any updates from the dev workshop that still need to be included here?

**Comment by DILewis** [comment]
> Pinging @lpugin @DILewis Any updates from the dev workshop that still need to be included here?

As indicated in the community meeting, at the dev workshop, we solidified a lot of stuff that needed implementation in the schema. We've been working on that, and hope to update this PR very soon. What we don't want to do is distract you folks with partial updates when a proper one is nearly done.

**Comment by musicEnfanthen** [comment]
OK, perfect. Many thanks for the feedback @DILewis . Looking forward to your update. 👍

**Comment by musicEnfanthen** [comment]
@musicog This PR is superseded by #1468, right? So this one here can be closed?

**Comment by musicog** [comment]
@musicEnfanthen Agree (after consulting @DILewis @janjusolja @reinierdevalk), this PR can now be closed :-)

**Pull request closed without merging**
