### PR TITLE
Release v5.0

### PR DESCRIPTION
**Pull request by bwbohl**
finally…

### CODE REVIEW

**Comment by ahankinson** [comment]
Fantastic!!!!! Well done @bwbohl and @musicEnfanthen

**Comment by kepper** [comment]
Hooray! My heroes 👍

**Comment by ahankinson** [comment]
Weirdly, these changes aren't appearing on stable yet...

**Comment by musicEnfanthen** [comment]
No, they don't. The PR merge and the release tag did not trigger the workflows correctly, so we needed to reset the merge for now.

**Comment by musicEnfanthen** [comment]
Follow-up PR to fix the workflows: #1332

**Comment by musicEnfanthen** [comment]
Superseded by #1333

**Pull request merged**
