### PR TITLE
Clarify remarks for elements based on other standards

### LINKED ISSUE #878: Clarify remarks for elements that are modelled after other standards
Some elements in MEI are modelled after other standards, e.g. [exhibHist](https://music-encoding.org/guidelines/dev/elements/exhibHist.html), however, the remarks do not seem to specify the exact element(s) that were used as templates for modelling and neither give the exact version of the respective standard used. These information would be helpful in order to provide sufficient descriptions for the guidelines and enable a better understanding of the elements for anyone not involved in the initial modelling process.

### PR DESCRIPTION
**Pull request by doerners**
This PR hopefully implements the task given in #878 and clarified in #1002 sufficiently.

Closes #878 
Closes #1002

### CODE REVIEW

**Review by kepper — DISMISSED** [review]
Many, many thanks, @doerners – good job, especially with pulling out the links for multiple other standards 👍

**Review by pe-ro — CHANGES_REQUESTED** [review]
The word "respective" isn't necessary.
```
"The model of this element is based on the 
<ref target="https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-teiCorpus.html">teiCorpus</ref> 
element of the Text Encoding Initiative (TEI).
```
is better.

**Comment by doerners** [comment]
As per @pe-ro's request I deleted the term "respective" and am kindly asking both @kepper and @pe-ro to have another look :)

**Review by pe-ro — APPROVED** [review]
Looks good.  Thanks.

**Comment by musicEnfanthen** [comment]
@kepper Your previous approval was discarded by GitHub after the latest changes by @doerners . May I ask you to re-review? Many thanks.

**Comment by musicEnfanthen** [comment]
Closes https://github.com/music-encoding/guidelines/issues/189

**Review by bwbohl — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
Thank you everyone!

**Pull request merged**
