### PR TITLE
Fix odd validation on constraint in mensural module

### LINKED ISSUE #789: Validation error in MEI.mensural.xml
There are 4 validation errors within `att.duration.quality` connected to wrong encoding of `constraintSpec`. 
@martha-thomae please fix.

### PR DESCRIPTION
**Pull request by rettinghaus**
After some more attempts I finally was able to fix the ODD. 
closes #789

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
@rettinghaus thank you! Could you add the scope of this PR (mensural) to its title?

@martha-thomae Maybe you could have a look (or someone else from @music-encoding/ig-mensural)?

**Comment by martha-thomae** [comment]
Great! Thanks, @rettinghaus!
Yes, I might be able to check this over the weekend. If anyone else from the @music-encoding/ig-mensural can see it earlier, they are welcome to do it :)

**Comment by annplaksin** [comment]
Hopefully, I understand the issue correctly:
As far, it seems the validation errors in the older version are fixed. I built the schema and tested the constraints. It seems they work fine now.

I only recognized some issues concerning the customization path in this branch... just to mention it after @bwbohl fixed the windows situation lately. This hasn't anything to do with this, I was just wondering...

**Comment by bwbohl** [comment]
you mean the changes to build.xml are not present here and you would need a rebase of this branch in order to build on your windows machine?

**Comment by annplaksin** [comment]
@bwbohl I don't think so, your changes are there. As kind of an uneducated guess, I am not sure whether cbc7901c39f1fb9b5d35ce7791fcab527ef02c81 might have to do something with it. It broke again because of the paths. Should I make another issue for this or should I wait with testing it again when you are finished with whatever you are doing now? It might be more useful to not highjack this pr too much...

**Comment by rettinghaus** [comment]
@annplaksin That's a different issue that should have a separate PR.

**Review by martha-thomae — APPROVED** [review]
I have reviewed this PR and everything seems ok. Thanks, @rettinghaus! 

I do remember that @kepper said that he was going to look into this issue and he had a [draft PR](https://github.com/music-encoding/music-encoding/pull/806#issue-905170593), in case he wants to take a look too. But, from my side, everything seems fine and I would merge it!

**Comment by kepper** [comment]
many thanks everyone :)

**Pull request merged**
