### PR TITLE
Fixed: Fixed tuplets in the Schubert Lindenbaum example

### PR DESCRIPTION
**Pull request by dinamix1**
Previously the tuplets in the measures 4 and 8 were not properly encoded. On measure 4, the final g was missing and on measure 8, it was not included in the tuplet.

### CODE REVIEW

**Comment by lpugin** [comment]
There are also some new 2012 examples, aren't there? Do we want this? Shouldn't we have them in 2013 version directly?

**Comment by dinamix1** [comment]
We only changed the mistakes in the 2013 version. Would you like them to be changed in the 2012 version as well?

**Comment by lpugin** [comment]
I am seeing new files (samples/MEI2012/Handcodings/Schubert_Erlkönig.mei) in the 5 files changed.

**Comment by lpugin** [comment]
Sorry, I just understood, one commit is about the change in the filename. Did you want to change this as well?

**Comment by ahankinson** [comment]
The ö in Erlkönig seemed to be causing some problems with git, and the file was showing up as marked for deletion. I think re-committing it fixed that issue.

**Pull request merged**
