### PR TITLE
schema: update license version and add publicationStmt to customizations

### PR DESCRIPTION
**Pull request by rettinghaus**
This adds `publisher` and `licence` information into the customization ODDs.

Additionally this fixes all license version statements.

### CODE REVIEW

**Review by bwbohl — DISMISSED** [review]

**Comment by musicEnfanthen** [comment]
@rettinghaus the source files are licensed under ecl 2.0 and here we have v1.0. Do we want to update version number here as well?

**Comment by rettinghaus** [comment]
@musicEnfanthen Good thing you noticed, because there was an ambiguity in all files.

**Review by bwbohl — DISMISSED** [review]

**Comment by bwbohl** [comment]
@musicEnfanthen please have a second look now that the version number is unified

**Comment by musicEnfanthen** [comment]
@bwbohl @rettinghaus shoot, having a second look, I see that the v1 reference was targetting the "derivation statement", i.e., the earlier versions that indeed were released under v1 of the ECL:

```
This is a derivative work based on earlier versions of the schema © 2001-2006 Perry Roland
and the Rector and Visitors of the University of Virginia; licensed under the Educational
Community License version 1.0.
```

So the statement was technically correct? (Sorry for the confusion)

**Comment by rettinghaus** [comment]
I guess you're right again @musicEnfanthen. Now everything should be fine.

**Review by bwbohl — APPROVED** [review]
thx for having a second look @musicEnfanthen and thx to @rettinghaus for fixing there and back again ;-)

**Review by musicEnfanthen — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
Thank you!

**Pull request merged**
