### PR TITLE
Update 01-introduction.xml

### PR DESCRIPTION
**Pull request by apacha**
Fixed a minor typo in the documentation: "...which features and solutions are appropriate to the task and should to be used" -> "...which features and solutions are appropriate to the task and should be used".

### CODE REVIEW

**Review by rettinghaus — APPROVED** [review]
Well spotted, thanks!

**Review by ahankinson — APPROVED** [review]

**Comment by ahankinson** [comment]
Minor correction. Two reviews. Merging.

**Comment by musicEnfanthen** [comment]
@ahankinson Did you close the PR without merging by accident?

**Comment by ahankinson** [comment]
D'oh. Yes.

**Comment by musicEnfanthen** [comment]
Thank you @apacha , @rettinghaus and @ahankinson !

**Pull request merged**
