### PR TITLE
schema: fix typo in description

### LINKED ISSUE #1447: Wrong explanation of `@lry`
In the guidelines it says

`@lry: indicates the lower-left corner x coordinate`

but it must be lower right-corner y coordinate

### PR DESCRIPTION
**Pull request by rettinghaus**
Closes #1447.

### CODE REVIEW

**Review by pe-ro — DISMISSED** [review]
Well caught and resolved. Thanks.

**Comment by obertsalome** [comment]
thank you for reacting and fixing it so quickly!
it must be `lower **right**-corner x-coordinate`, right?

**Comment by rettinghaus** [comment]
@obertsalome right again! Thanks for checking.

**Comment by rettinghaus** [comment]
For reference: TEI makes it more clear imho: 

> gives the x coordinate value for the lower right corner of a rectangular space

**Review by bwbohl — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
Just to be sure, since this conversation here speaks always of the x-coordinate: you all mean the y coordinate, right?

**Review by pe-ro — APPROVED** [review]
Looks good to me.

**Comment by pe-ro** [comment]
@musicEnfanthen, yes, lower right Y.

**Comment by bwbohl** [comment]
the code is clear about that ;-)

**Pull request merged**
