### PR TITLE
utils: remove unnecessary type attribute on script

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
Thanks @rettinghaus. Can you please clean up the remaining occurrences in comparison.xsl as well?

https://github.com/music-encoding/music-encoding/blob/f5224596d403f43027062e93aec06b73c7be3528/utils/compare_versions/comparison.xsl#L71-L72

https://github.com/music-encoding/music-encoding/blob/f5224596d403f43027062e93aec06b73c7be3528/utils/compare_versions/comparison.xsl#L104

**Comment by rettinghaus** [comment]
done

**Comment by musicEnfanthen** [comment]
Thx. You prefer to keep the type attribute in line 72 or just missed it?

**Comment by musicEnfanthen** [comment]
Perfect, thanks!

**Review by musicEnfanthen — APPROVED** [review]

**Review by bwbohl — APPROVED** [review]

**Pull request merged**
