### PR TITLE
Remove "italic" and "oblique" values from data.TEXTRENDITIONLIST

### LINKED ISSUE #1102: Available values in data.TEXTRENDITIONLIST
I there a difference in using `<rend fontstyle="italic">` or `<rend rend="italic">`?

Some values in `data.TEXTRENDITIONLIST` duplicating font styling properties.

### PR DESCRIPTION
**Pull request by pe-ro**
The values "italic" and "oblique" duplicate values available in data.FONTSTYLE.

Fixes #1102

### CODE REVIEW

**Review by rettinghaus — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
@kepper can you take care of the transformation propsed in #1102?

**Comment by bwbohl** [comment]
Converted to draft: please add the xslt update to this PR directly or via pull request

**Review by bwbohl — CHANGES_REQUESTED** [review]
please also update the xslt for conversion from v4 to v5 accordingly

**Comment by ahankinson** [comment]
> Converted to draft: please add the xslt update to this PR directly or via pull request

Note that the XSLT is in a different repo: https://github.com/music-encoding/encoding-tools/pull/30

**Review by bwbohl — APPROVED** [review]

**Comment by bwbohl** [comment]
During a second view @musicEnfanthen, @kepper and I discovered that while this proposal is good, it still needs to resolve the situation fully. (see also the comment at https://github.com/music-encoding/encoding-tools/pull/30#issuecomment-1592024516)
Making this a bigger and more substantial change, e.g. bold to `@fontweight`, and maybe even split the `@rend` values to two separate definitions – one for `del` and one for `rend`. This will not make it into MEI 5.0, though. But would be a candidate for MEI 5.x.
Thus reverting this merge, reopening the PR and converting it to a draft.

**Comment by musicEnfanthen** [comment]
Explanation for reversion given in https://github.com/music-encoding/music-encoding/pull/1188#issuecomment-1592045421. We should address this topic more broadly for the next release after v5.

**Pull request merged**
