### PR TITLE
fix typo in html class

### PR DESCRIPTION
**Pull request by rettinghaus**
This is a first step in fixing https://github.com/music-encoding/music-encoding.github.io/issues/303

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
Thank you @rettinghaus for the catch! Can confirm that removal of the obviously wrong class fixes the appending of the searchmenu at the bottom.

For the alignment of the search input, can you try the following, please:

Add a `class="search_input"` to the following two lines in `utils/guidelines_xslt/odd2html/htmlFile.xsl` (find by id):


`<input id="search_inputTop"  title="At least 3 characters" type="text"></input>`

`<input name="q" id="search_input" title="At least 3 characters" type="text"></input>` (probably the `name="q"` can be removed here as well?)

Then, in [search.css](https://music-encoding.org/guidelines/dev/css/search.css) replace the CSS rules under "search box" with the following:
```
/* search box */

.search_input {
	float: left;
	width: 200px;
	height: 1.4rem;
	background-color: #ffffff;
	border-radius: 3px;
	border: .5px solid #213b9d;
	box-sizing: border-box;
	-moz-appearance: none;
	-webkit-appearance: none;
	padding: .2rem .5rem .2rem .5rem;
	outline: 0;
	margin: 0;
}

search_button {
	position: inherit;
	height: 1.4rem;
	margin-left: -3px;
	padding: 1.5px 5px 3px 5px;
	background-color: #2440aa; 
	border: .5px solid #213b9d;
	border-radius: 0 3px 3px 0;
	box-sizing: border-box;
	cursor: pointer;
}

.search_icon {
    transform: rotate(-45deg);
    float: left;
    -moz-appearance: none;
    -webkit-appearance: none;
    box-sizing: border-box;
    box-shadow: none;
    color: #ffffff;
}

```

**Comment by rettinghaus** [comment]
@musicEnfanthen Thank you. Yes, this fixes the side-bar issue. 
Thanks also for the suggestion, I wanted to test it properly and save it for a second PR.

**Review by musicEnfanthen — APPROVED** [review]
Obvious error, thanks for the catch.

**Comment by musicEnfanthen** [comment]
Agreed, let's fix the search bar in a second PR.

**Comment by rettinghaus** [comment]
@musicEnfanthen could you please open a PR with your proposals for `search_input` you made earlier. I don't find the time at the moment.

**Comment by musicEnfanthen** [comment]
@rettinghaus Thanks. PR prepared in #953

**Pull request merged**
