### PR TITLE
schema: change rng:empty to tei:empty

### PR DESCRIPTION
**Pull request by rettinghaus**
Another try to make a small step towards pureODD. 

Doesn't affect anything, just a small namespace clean-up in our ODDs.
See #1050 and #1164

### CODE REVIEW

**Review by bwbohl — APPROVED** [review]

**Comment by rettinghaus** [comment]
@musicEnfanthen?

**Comment by musicEnfanthen** [comment]
Thank you @rettinghaus . In general, I am inclined to leave pureODD transformation for a time after a potential 5.1 release. 

Since your proposed changes are very focused in scope, they do not seem to do any harm, on the other hand. 

Just to double-check: Could this change lead to a conflicting situation for the next release where we end up with some parts of the schema not "cooperating" very well?

**Comment by rettinghaus** [comment]
@musicEnfanthen No, there shouldn't be any problem at all. What were you thinking of specifically? Could you please elaborate a bit?

**Comment by bwbohl** [comment]
> Thank you @rettinghaus . In general, I am inclined to leave pureODD transformation for a time after a potential 5.1 release.
> 
> Since your proposed changes are very focused in scope, they do not seem to do any harm, on the other hand.
> 
> Just to double-check: Could this change lead to a conflicting situation for the next release where we end up with some parts of the schema not "cooperating" very well?

@musicEnfanthen this change is at the very detail level of the ODD and since an empty element is just –empty– it does not make any difference whether emptiness is defined with `rng:empty` or `tei:empty`.

**Comment by musicEnfanthen** [comment]
Perfect, thank you @rettinghaus and @bwbohl !

**Review by musicEnfanthen — APPROVED** [review]

**Pull request merged**
