### PR TITLE
Add glossaries to attribute definitions

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR adds glossaries to some attributes that contain their full name.

### CODE REVIEW

**Review by pe-ro — DISMISSED** [review]
These glosses are fine, but we may just be buying ourselves additional issues with rendering the documentation.

**Review by bwbohl — DISMISSED** [review]

**Comment by musicEnfanthen** [comment]
@rettinghaus Could you fix the merge conflict?

**Comment by musicEnfanthen** [comment]
@pe-ro @bwbohl May I ask you to re-review since your former approvals have been dismissed by the latest changes.

**Review by pe-ro — APPROVED** [review]
Looks good.

**Review by bwbohl — APPROVED** [review]

**Pull request merged**
