### PR TITLE
Add description for MEI virtual unit

### LINKED ISSUE #782: Add explanation of virtual units to Guidelines
This is a a suggestion I brought up in the last ODD meeting, linked to #733 
Might it be possible to add some explanation of using virtual units into the Guidelines that is not hidden in the attribute specs?

### PR DESCRIPTION
**Pull request by doerners**
This PR adds a description of the nature of MEI virtual unit to chapter 3 of the Guidelines.
Closes #782

### CODE REVIEW

**Review by rettinghaus — APPROVED** [review]
Looks good to me, thanks!

**Comment by musicEnfanthen** [comment]
Thank you @doerners .

Please note that there is also https://github.com/music-encoding/music-encoding/blob/374ce487fd0a8041e9f01db5a61266889362b847/source/modules/MEI.visual.xml#L1493-L1496

Maybe it's possible to harmonize the wording in all three passages to avoid diverging interpretations?

**Comment by bwbohl** [comment]
In terms of harmonisation I'd prefer the "middle" of the staffline, because then page orientation is not of importance.
If you would be so kind as to harmonise it in the other spots (visual and shared)

**Comment by bwbohl** [comment]
2022-02-24 ODD meeting: As soon as it's done and reviewed we can merge it.

**Review by rettinghaus — APPROVED** [review]

**Review by musicEnfanthen — APPROVED** [review]
Looks good. Thank you @doerners

**Pull request merged**
