### PR TITLE
Made ornament visual classes members of att.atlsym. 

### PR DESCRIPTION
**Pull request by raffazizzi**
Fixes issue #232

### CODE REVIEW

**Comment by ahankinson** [comment]
Changing to `Needs Review` so that it's clear that someone should review the patch and comment. `Needs Discussion` should probably be reserved for issues... 

#growingpains

**Comment by ahankinson** [comment]
Since this is our first go-round with this type of development, I'm wondering if we should also ask for a small example file that will fail validation without this patch, but pass with this patch. These test cases could then form the basis of an automated unit testing system...

**Comment by raffazizzi** [comment]
Good idea :+1:

I added a test file, let me know if you think it should be in a different location.

I also regenerated the schema... this is another thing we should request when submitting a fix: regenerate at least mei-all.rng to show that there are no errors introduced in the schema generation.

**Comment by ahankinson** [comment]
Hm. I wonder if this should in fact go in a top-level `tests` directory, and not in the sample encodings. 

It should also probably have the pull request number in it somewhere, just so we can find the reason for the file later if we need to.

**Comment by ahankinson** [comment]
BTW, if you branch locally for a specific fix and don't issue your pull request from your own `master` branch but from your local issue-specific branch, you won't need to do a merge if things change upstream...

**Comment by ahankinson** [comment]
Other than that, looks great!

**Comment by raffazizzi** [comment]
> Hm. I wonder if this should in fact go in a top-level tests directory, and not in the sample encodings.

I had the same thought, but then aren't the samples tests themselves when it comes to check for schema validity / coherence? That's why I thought bundling them together might make sense. Maybe.

**Comment by ahankinson** [comment]
RE: Schema re-generation, we've got the Jenkins CI server set up to do this for us:

http://dev.simssa.ca:8080/jenkins/

I've not updated it to pull from GitHub yet, but it will re-compile and re-validate all the samples from the latest commit of the MEI source and customizations.

http://dev.simssa.ca:8080/jenkins/job/music-encoding-initiative/48/console

**Comment by raffazizzi** [comment]
RE: Jenkins, cool, but it would only kick off after the PR is merged right? Or is there a way to test the PR on Jenkins before merging?

**Comment by ahankinson** [comment]
I think Jenkins can be configured to test PRs and report back on their status. Failing that, there's also TravisCI

**Pull request closed without merging**
