### PR TITLE
Added abbreviation tags to MARC

### PR DESCRIPTION
**Pull request by rettinghaus**
Links may be added after discussion in #878.

### CODE REVIEW

**Comment by bwbohl** [comment]
I see the sense in tagging MARC in order to make it possible to e.g. index it but would there be a semantically stronger option than `abbr`?  What about `term`?

**Comment by bwbohl** [comment]
I thinks it's worthwhile to consider deeper and semantically richer tagging of the guidelines but maybe we should come up with a clear concept what we want to achieve with it rather earlier than later as TEI offers such a rich tags for so many purposes…

**Comment by doerners** [comment]
Since MARC is short for **MA**chine **R**eadable **C**ataloguing I'd argue that technically `<abbr>` isn't wrong nor imprecise here. Considering the examples given for [`<term>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-term.html) within the TEI guidelines I'd say it doesn't really apply entirely to the MARC example here.

I like the idea of having a glossary as some of the TEI examples refer to. We might think about building a glossary for MEI, however, my intuition would be to focus more on the musical terms that are not abbreviations but of technical nature.

**Comment by bwbohl** [comment]
ok, let's go with the abbreviation for a term ;-)

**Comment by bwbohl** [comment]
Strategy then should be to markup similar abbreviations and likewise terms if they appear, then use a script to collect them all and then enhance the encoding with some key. an then enable automatic compilation of indices across the guidelines

**Review by bwbohl — DISMISSED** [review]

**Review by kepper — APPROVED** [review]
sounds wonderful, thanks!

**Comment by bwbohl** [comment]
just to link it, this goes hand in hand with #913

**Review by bwbohl — APPROVED** [review]

**Pull request merged**
