### PR TITLE
allow color on key signatures

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR makes  `att.keyAccid.vis` and `att.keySig.vis` member of `att.color`.

### CODE REVIEW

**Comment by rettinghaus** [comment]
@bwbohl could you check and approve?

**Comment by ahankinson** [comment]
Is there an issue or some other explanation of the reason for this change available?

**Comment by rettinghaus** [comment]
I didn't open another issue for this, as I thought it would be self-explanatory. 
Refers to issues #346 #517 #518 #524

**Comment by ahankinson** [comment]
Great, that's all I needed -- just some reference so that we have a record of why the change is being requested.

**Review by ahankinson — APPROVED** [review]

**Comment by rettinghaus** [comment]
Thanks!

**Pull request merged**
