### PR TITLE
Release 4.0.1

### PR DESCRIPTION
**Pull request by ahankinson**
This PR includes the fixes to create MEI 4.0.1, a bugfix release to fix a problem with schema generation.

### CODE REVIEW

**Comment by ahankinson** [comment]
Please do not merge until we have consensus on this. If you have any objections I would suggest a 72h window for comments.

**Review by kepper — APPROVED** [review]
I've investigated a couple of hours now, but I can't find the other thing that seemed like an urgent bug in need of fixing anymore. It was spotted by @aseipelt, but she'll be out of office before this needs to be resolved. Worst case will thus be another bugfix release…

**Comment by ahankinson** [comment]
@lpugin @bwbohl could you please indicate approval (or not?)

@music-encoding/core-contributors anyone else can thumbs-up or approve as well.

**Review by lpugin — APPROVED** [review]
Looks good to me

**Comment by ahankinson** [comment]
I believe we'll also need to re-generate the RNG?

**Review by bwbohl — APPROVED** [review]

**Comment by ahankinson** [comment]
I'll re-generate the RNG and put it in the Pull Request too

**Pull request merged**
