### PR TITLE
Remove fontname attribute

### LINKED ISSUE #716: deprecate fontname
As @th-we pointed out in https://github.com/music-encoding/music-encoding/pull/704#issue-469038961, we still do have both `@fontfam` and `@fontname`. The latter is a very old artifact, and there is no corresponding attribute / value in TEI or CSS. Both are defined in the same attribute class [att.typography](https://music-encoding.org/guidelines/v4/attribute-classes/att.typography.html), which means they are always available in the same spaces. There seems absolutely no reason to preserve both, and I recommend to go with `@fontfam`, and drop `@fontname`. Taking this out will change "forward compatibility", but an automatic conversion seems easy, so that shouldn't be an issue.

### PR DESCRIPTION
**Pull request by kepper**
fixes #716

### CODE REVIEW

**Comment by rettinghaus** [comment]
This breaks backwards compatibility and should go into MEI5.

**Comment by kepper** [comment]
During ODD Thursday on Oct 29, we decided that this should be merged only if there are other breaking changes in the specs already. If not, it will be set aside for later consideration.

**Comment by kepper** [comment]
one question to @lpugin: Does Verovio support both `@fontname` and `@fontfam`? There is at least one example in the Guidelines that uses `@fontname`, and it would be good to know if this would break more than just backwards compatibility ;-)

**Comment by lpugin** [comment]
Verovio uses `@fontname`, but this is easy to change. Since Verovio is currently aligned with the develop version of MEI we can break compatibility without problem. Thanks for asking.

Regarding the example we can see, but I would suggest to drop it in the new version of the guidelines. In the end it would probably be simpler to have only examples images generated with Meiler. We can see this next week.

**Comment by bwbohl** [comment]
probably should be closed in favour of #897 ? Could you clarify?

**Comment by bwbohl** [comment]
closed in favour of #897

**Pull request closed without merging**
